# Generated by Django 4.2.1 on 2023-05-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('autor', models.CharField(max_length=10)),
                ('editorial', models.CharField(max_length=250)),
                ('ncapitulos', models.IntegerField()),
                ('npaginas', models.IntegerField()),
                ('isbn', models.IntegerField()),
                ('actual', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
